// Static listings data for Nassira Properties
export const staticListings = [
  {
    id: 1,
    type: "VILLA",
    status: "FOR SALE",
    price: "AED 32,000,000",
    title: "Luxury Villa in Palm Jumeirah",
    location: "Palm Jumeirah, Dubai, United Arab Emirates",
    beds: 5,
    baths: 6,
    sqft: 8500,
    image: "/images/palm-jumeirah-villa.jpg",
  },
  {
    id: 2,
    type: "APARTMENT",
    status: "FOR SALE",
    price: "AED 4,500,000",
    title: "Modern Apartment in Downtown Dubai",
    location: "Downtown Dubai, Dubai, United Arab Emirates",
    beds: 2,
    baths: 3,
    sqft: 1800,
    image: "/images/downtown-apartment.jpg",
  },
  {
    id: 3,
    type: "PENTHOUSE",
    status: "FOR SALE",
    price: "AED 18,000,000",
    title: "Exclusive Penthouse with Burj Khalifa View",
    location: "Business Bay, Dubai, United Arab Emirates",
    beds: 4,
    baths: 5,
    sqft: 5200,
    image: "/images/penthouse-business-bay.jpg",
  },
  {
    id: 4,
    type: "VILLA",
    status: "FOR SALE",
    price: "AED 25,000,000",
    title: "Beachfront Villa in Jumeirah Golf Estate",
    location: "Jumeirah Golf Estate, Dubai, United Arab Emirates",
    beds: 6,
    baths: 7,
    sqft: 9200,
    image: "/images/jumeirah-golf-villa.jpg",
  },
  {
    id: 5,
    type: "APARTMENT",
    status: "FOR RENT",
    price: "AED 120,000/year",
    title: "2BR Apartment Dubai Marina",
    location: "Dubai Marina, Dubai, United Arab Emirates",
    beds: 2,
    baths: 2,
    sqft: 1450,
    image: "/images/marina-apartment.jpg",
  },
  {
    id: 6,
    type: "TOWNHOUSE",
    status: "FOR SALE",
    price: "AED 8,500,000",
    title: "Spacious Townhouse in Dubai Hills",
    location: "Dubai Hills, Dubai, United Arab Emirates",
    beds: 4,
    baths: 5,
    sqft: 3800,
    image: "/images/dubai-hills-townhouse.jpg",
  },
  {
    id: 7,
    type: "VILLA",
    status: "FOR SALE",
    price: "AED 45,000,000",
    title: "Ultra-Luxury Villa Emirates Hills",
    location: "Emirates Hills, Dubai, United Arab Emirates",
    beds: 7,
    baths: 8,
    sqft: 12000,
    image: "/images/emirates-hills-villa.jpg",
  },
  {
    id: 8,
    type: "APARTMENT",
    status: "FOR SALE",
    price: "AED 6,200,000",
    title: "3BR Penthouse Bluewaters",
    location: "Bluewaters Island, Dubai, United Arab Emirates",
    beds: 3,
    baths: 4,
    sqft: 2800,
    image: "/images/bluewaters-apartment.jpg",
  },
  {
    id: 9,
    type: "VILLA",
    status: "FOR RENT",
    price: "AED 650,000/year",
    title: "5BR Luxury Villa District One",
    location: "District One, Dubai, United Arab Emirates",
    beds: 5,
    baths: 6,
    sqft: 7800,
    image: "/images/district-one-villa.jpg",
  },
  {
    id: 10,
    type: "APARTMENT",
    status: "FOR SALE",
    price: "AED 2,800,000",
    title: "Studio in Downtown Dubai",
    location: "Downtown Dubai, Dubai, United Arab Emirates",
    beds: 0,
    baths: 1,
    sqft: 850,
    image: "/images/downtown-studio.jpg",
  },
  {
    id: 11,
    type: "VILLA",
    status: "FOR SALE",
    price: "AED 38,000,000",
    title: "Signature Villa Saadiyat Island",
    location: "Saadiyat Island, Abu Dhabi, United Arab Emirates",
    beds: 6,
    baths: 7,
    sqft: 9500,
    image: "/images/saadiyat-villa.jpg",
  },
  {
    id: 12,
    type: "TOWNHOUSE",
    status: "FOR SALE",
    price: "AED 12,500,000",
    title: "4BR Townhouse Palm Jumeirah",
    location: "Palm Jumeirah, Dubai, United Arab Emirates",
    beds: 4,
    baths: 4,
    sqft: 4200,
    image: "/images/palm-townhouse.jpg",
  },
  {
    id: 13,
    type: "APARTMENT",
    status: "FOR RENT",
    price: "AED 180,000/year",
    title: "3BR Apartment Business Bay",
    location: "Business Bay, Dubai, United Arab Emirates",
    beds: 3,
    baths: 3,
    sqft: 2200,
    image: "/images/business-bay-rental.jpg",
  },
  {
    id: 14,
    type: "PENTHOUSE",
    status: "FOR SALE",
    price: "AED 55,000,000",
    title: "Duplex Penthouse Burj Khalifa Views",
    location: "Downtown Dubai, Dubai, United Arab Emirates",
    beds: 5,
    baths: 6,
    sqft: 6800,
    image: "/images/burj-penthouse.jpg",
  },
  {
    id: 15,
    type: "VILLA",
    status: "FOR RENT",
    price: "AED 450,000/year",
    title: "6BR Villa Yas Island",
    location: "Yas Island, Abu Dhabi, United Arab Emirates",
    beds: 6,
    baths: 6,
    sqft: 6800,
    image: "/images/yas-island-villa.jpg",
  },
  {
    id: 16,
    type: "APARTMENT",
    status: "FOR SALE",
    price: "AED 3,500,000",
    title: "2BR Apartment Marina Walk",
    location: "Dubai Marina, Dubai, United Arab Emirates",
    beds: 2,
    baths: 2,
    sqft: 1600,
    image: "/images/marina-walk-apartment.jpg",
  },
  {
    id: 17,
    type: "VILLA",
    status: "FOR SALE",
    price: "AED 28,000,000",
    title: "Beach Villa Jumeirah Beach Road",
    location: "Jumeirah, Dubai, United Arab Emirates",
    beds: 5,
    baths: 5,
    sqft: 7200,
    image: "/images/jumeirah-beach-villa.jpg",
  },
  {
    id: 18,
    type: "TOWNHOUSE",
    status: "FOR RENT",
    price: "AED 320,000/year",
    title: "4BR Townhouse Arabian Ranches",
    location: "Arabian Ranches, Dubai, United Arab Emirates",
    beds: 4,
    baths: 4,
    sqft: 3500,
    image: "/images/arabian-ranches-townhouse.jpg",
  },
]

export const getListingsData = () => {
  // Extract unique areas and cities from listings
  const areasSet = new Set<string>()
  const citiesSet = new Set<string>()

  staticListings.forEach((listing) => {
    const locationParts = listing.location.split(",").map((part) => part.trim())
    if (locationParts.length > 0 && locationParts[0]) {
      areasSet.add(locationParts[0])
    }
    if (locationParts.length > 1 && locationParts[1]) {
      citiesSet.add(locationParts[1])
    }
  })

  const areas = Array.from(areasSet).sort()
  const cities = Array.from(citiesSet).sort()

  return {
    listings: staticListings,
    areas,
    cities,
    count: staticListings.length,
  }
}

