import * as fs from 'fs';
import * as path from 'path';

type Listing = {
  id: number;
  type: string;
  status: 'FOR SALE' | 'FOR RENT';
  price: string;
  title: string;
  location: string;
  beds: number;
  baths: number;
  sqft: number;
  image: string;
  url?: string;
};

const INPUT_FILE = '/tmp/all_listings_final.json';
const OUTPUT_FILE = path.join(process.cwd(), 'lib', 'listings-data.ts');

function uniqBy<T>(arr: T[], key: (x: T) => string | number): T[] {
  const seen = new Set<string | number>();
  return arr.filter((x) => {
    const k = key(x);
    if (seen.has(k)) return false;
    seen.add(k);
    return true;
  });
}

function generateFileContent(listings: Listing[]): string {
  const header = `// Static listings data for Nassira Properties
// Auto-generated by CI. Do not edit manually.
// Last updated: ${new Date().toISOString()}
// Total listings: ${listings.length} (${listings.filter(l => l.status === 'FOR SALE').length} for sale, ${listings.filter(l => l.status === 'FOR RENT').length} for rent)
// Source: PropertyFinder - Nassira Realty Group

export const staticListings = ${JSON.stringify(listings, null, 2)} as const;

export const getListingsData = () => {
  // Extract unique areas and cities from listings
  const areasSet = new Set<string>();
  const citiesSet = new Set<string>();

  staticListings.forEach((listing) => {
    const locationParts = listing.location.split(",").map((part) => part.trim());
    if (locationParts.length > 0 && locationParts[0]) {
      areasSet.add(locationParts[0]);
    }
    if (locationParts.length > 1 && locationParts[1]) {
      citiesSet.add(locationParts[1]);
    }
  });

  const areas = Array.from(areasSet).sort();
  const cities = Array.from(citiesSet).sort();

  return {
    listings: staticListings,
    areas,
    cities,
    count: staticListings.length,
  };
};
`;

  return header;
}

async function main() {
  try {
    // Check if input file exists
    if (!fs.existsSync(INPUT_FILE)) {
      console.error(`❌ Input file not found: ${INPUT_FILE}`);
      console.error('Make sure to run scripts/get-all-58-listings.js first');
      process.exit(1);
    }

    // Read and parse JSON
    console.log(`📖 Reading listings from ${INPUT_FILE}...`);
    const rawData = fs.readFileSync(INPUT_FILE, 'utf-8');
    let listings: Listing[] = JSON.parse(rawData);

    // Validate listings
    if (!Array.isArray(listings)) {
      console.error('❌ Invalid JSON format: expected array');
      process.exit(1);
    }

    console.log(`📊 Processing ${listings.length} listings...`);

    // Deduplicate by ID and sort
    listings = uniqBy(listings, (l) => l.id);
    listings.sort((a, b) => a.id - b.id);

    console.log(`✅ Processed ${listings.length} unique listings`);
    console.log(`   For Sale: ${listings.filter(l => l.status === 'FOR SALE').length}`);
    console.log(`   For Rent: ${listings.filter(l => l.status === 'FOR RENT').length}`);

    // Generate TypeScript file
    const content = generateFileContent(listings);
    
    // Ensure output directory exists
    const outputDir = path.dirname(OUTPUT_FILE);
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    // Write file
    fs.writeFileSync(OUTPUT_FILE, content, 'utf-8');
    console.log(`\n✅ Successfully generated ${OUTPUT_FILE}`);
    console.log(`   Total listings: ${listings.length}`);
  } catch (error: any) {
    console.error('❌ Error:', error.message);
    if (error.stack) {
      console.error(error.stack);
    }
    process.exit(1);
  }
}

main();

